### ISSUE TITLE
querySelectorAll in LazyOrgChart update override is failing

### ISSUE THREAD

**Issue by tlockhart** [m-gallesio/d3-org-chart-lazy#1]
I am receiving the following error when attemting to render my nodes with the LazyOrgChart from d3-org-chart-lazy package.

d3-org-chart-lazy.esm.js:53 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': '[object HTMLDivElement] .node-button-g' is not a valid selector.
    at LazyOrgChart.update (http://localhost:3000/static/js/bundle.js:220651:33)
    at LazyOrgChart.render (http://localhost:3000/static/js/bundle.js:112487:10)
    
Changing the query to this worked for me:

```
const chartState = this.getChartState();
const containerElem = chartState.container;
for (const node of containerElem.querySelectorAll('.node-button-g')) {
```

**Comment by m-gallesio** [comment]
Greetings.
Indeed, I had not noticed the `container` property can be a DOM element and not only a CSS selector.

I am working on this. I also plan to update the typings for `d3-org-chart` on DefinitelyTyped to reflect this finding.

**Comment by m-gallesio** [comment]
I have published an updated version, please upgrade to `0.1.0`.

**Comment by tlockhart** [comment]
> I have published an updated version, please upgrade to `0.1.0`.

Thanks for the update!  Excellent work by the way it was just what I was looking for.  Have you considered making a numOfSubordinates property required in the data.  That way, if a node does not have any subordinates, there is no need to display the button, and the ones that do could display the button with the number of subordinates and actually perform a fetch of subordinates.  Once the fetch is complete the subordinates will be displayed in the chart.  This would give the appearance that the data is front loaded.  I am adding this feature in my branch.

**Comment by m-gallesio** [comment]
> That way, if a node does not have any subordinates, there is no need to display the button, and the ones that do could display the button with the number of subordinates and actually perform a fetch of subordinates.

I want to keep this as unobtrusive as possible and alter as little as possible the logic of the base library, so I do not like the idea of enforcing a required field. This is something I think consumers of the library should do.

Your use case should be already able to be handled by the `hasChildren` option, which could be as simple as providing this:
```
item => item.numOfSubordinates > 0
```

The appearance of the button can already be customized via the standard `buttonContent` option, which can just return an empty string if numOfSubordinates is 0. Our internal product uses this approach.

In the latest commit I have added a detailed readme which should cover firther questions.

**Comment by tlockhart** [comment]
Great thx!
